rules:
  at-rule-name-case:
    - lower
    - severity:
      - warning
  block-closing-brace-empty-line-before:
    - never
    - severity:
      - warning
  block-closing-brace-newline-after:
    - always
    - severity:
      - warning
  block-no-empty:
    - true
    - severity:
      - warning
  block-opening-brace-newline-after:
    - always-multi-line
    - severity:
      - warning
  block-opening-brace-newline-before:
    - never-single-line
    - severity:
      - warning
  block-opening-brace-space-after:
    - always-single-line
    - severity:
      - warning
  block-opening-brace-space-before:
    - always
    - severity:
      - warning
  color-hex-case:
    - lower
    - severity:
      - warning
  color-no-invalid-hex:
    - true
    - severity:
      - warning
  comment-empty-line-before:
    - always
    - severity:
      - warning
  comment-no-empty:
    - true
    - severity:
      - warning
  comment-whitespace-inside:
    - always
    - severity:
      - warning
  declaration-block-no-duplicate-properties:
    - true
    - severity:
      - warning
  declaration-block-no-ignored-properties:
    - true
    - severity:
      - warning
  declaration-block-no-shorthand-property-overrides:
    - true
    - severity:
      - warning
  declaration-block-semicolon-newline-after:
    - always-multi-line
    - severity:
      - warning
  declaration-block-trailing-semicolon:
    - always
    - severity:
      - warning
  declaration-colon-space-after:
    - always
    - severity:
      - warning
  declaration-colon-space-before:
    - never
    - severity:
      - warning
  declaration-empty-line-before:
    - never
    - severity:
      - warning
  font-family-name-quotes:
    - always-where-recommended
    - severity:
      - warning
  function-comma-space-after:
    - always
    - severity:
      - warning
  function-name-case:
    - lower
    - severity:
      - warning
  function-parentheses-space-inside:
    - never
    - severity:
      - warning
  function-url-quotes:
    - always
    - severity:
      - warning
  function-whitespace-after:
    - always
    - severity:
      - warning
  indentation:
    - 2
    - severity:
      - warning
  length-zero-no-unit: true
  max-empty-lines:
    - 2
    - severity:
      - warning
  max-nesting-depth:
    - 2
    - severity:
      - warning
  media-feature-no-missing-punctuation:
    - true
    - severity:
      - warning
  no-duplicate-selectors:
    - true
    - severity:
      - warning
  no-eol-whitespace:
    - true
    - severity:
      - warning
  no-extra-semicolons:
    - true
    - severity:
      - warning
  no-invalid-double-slash-comments:
    - true
    - severity:
      - warning
  no-missing-end-of-source-newline:
    - true
    - severity:
      - warning
  number-leading-zero: always
  number-no-trailing-zeros:
    - true
    - severity:
      - warning
  property-case: lower
  property-no-vendor-prefix:
    - true
    - severity:
      - warning
  rule-nested-empty-line-before:
    - always
    - except:
      - first-nested
    - ignore:
      - after-comment
    - severity:
      - warning
  rule-non-nested-empty-line-before:
    - always
    - ignore:
      - after-comment
    - severity:
      - warning
  selector-attribute-brackets-space-inside:
    - never
    - severity:
      - warning
  selector-attribute-operator-space-after:
    - never
    - severity:
      - warning
  selector-attribute-operator-space-before:
    - never
    - severity:
      - warning
  selector-attribute-quotes:
    - never
    - severity:
      - warning
  selector-class-pattern:
    - ^(?:(?:a|o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9\\@]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$
    - severity:
      - warning
  selector-combinator-space-after:
    - always
    - severity:
      - warning
  selector-combinator-space-before:
    - always
    - severity:
      - warning
  selector-list-comma-space-after:
    - always-single-line
    - severity:
      - warning
  selector-list-comma-space-before:
    - never
    - severity:
      - warning
  selector-max-compound-selectors:
    - 3
    - severity:
      - warning
  selector-max-empty-lines:
    - 0
    - severity:
      - warning
  selector-no-id: true
  selector-no-qualifying-type:
    - true
    - ignore:
      - attribute
    - severity:
      - warning
  selector-pseudo-class-case:
    - lower
    - severity:
      - warning
  selector-pseudo-class-no-unknown:
    - true
    - severity:
      - warning
  selector-pseudo-element-case:
    - lower
    - severity:
      - warning
  selector-type-case: lower
  selector-type-no-unknown:
    - true
    - severity:
      - warning
  string-no-newline:
    - true
    - severity:
      - warning
  string-quotes:
    - single
    - severity:
      - warning
  unit-case: lower
  unit-no-unknown:
    - true
    - severity:
      - warning
  value-keyword-case: lower
  value-list-comma-space-after:
    - always
    - severity:
      - warning
  value-list-comma-space-before:
    - never
    - severity:
      - warning
