language: node_js
node_js:
  - "7"
  - "6"
  - "4"
addons:
  apt:
    packages:
      - php5-cli
      - php5-mysql
services:
  - mysql
before_install:
  - npm install -g yo
matrix:
  include:
    - node_js: "6"
      env: TEST_VERSIONS=generator
    - node_js: "6"
      env: TEST_VERSIONS=generated_project
  allow_failures:
    - env: TEST_VERSIONS=generator
    - env: TEST_VERSIONS=generated_project
